# -------------------------------------------------------------------
# Task specific settings
# -------------------------------------------------------------------
debug:
  minimal: true
transpile:
  src: './model/**/*.js'
  dest: './.tmp/model'
lessReduce:
  src: './src/lib/less/**/_root.less'
  dest: './src/lib/css/style.css'
lessEach:
  src: './src/lib/less/**/*.less'
  dest: './src/lib/css'
